[server]
# Disable file watching to prevent watchdog errors on Windows
fileWatcherType = "none"

[theme]
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730" 